name: main
on:
  - pull_request
  - push
jobs:
  main:
    name: node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: node
      - run: npm install
      - run: npm test
      - uses: codecov/codecov-action@v3
      - run: npm config set access public
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

#    strategy:
#      matrix:
#        node:
#          - lts/erbium
#          - node

